---
default:
  image: docker-registry.eccenca.com/eccenca-python:v3.9.12-1

stages:
  - test
  - build
  - deploy

check:
  stage: test
  script:
    - task check
  artifacts:
    when: always
    reports:
      cobertura:
        - ./dist/coverage.xml
      junit:
        - ./dist/junit-bandit.xml
        - ./dist/junit-flake8.xml
        - ./dist/junit-mypy.xml
        - ./dist/junit-pylint.xml
        - ./dist/junit-pytest.xml
    paths:
      - ./dist/badge-coverage.svg
      - ./dist/badge-tests.svg
      - ./dist/coverage
      - ./dist/coverage.xml

build:
  stage: build
  script:
    - task build
  artifacts:
    when: always
    paths:
      - ./dist/*.tar.gz
      - ./dist/*.whl

pages:
  stage: deploy
  only:
    - master
    - main
  script:
    - task check
    - pip install mkdocs-material
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public

