site_name: cmem-plugin-docs
site_description: This eccenca Corporate Memory plugin totally rocks with all new
    docs support
site_author: Ranga Reddy Nukala
repo_url: https://github.com/irangareddy/cmem-plugin-docs
site_url: https://irangareddy.github.io/cmem-plugin-docs/
repo_name: cmem-plugin-docs
site_dir: site

theme:
  name: material
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/git-alt


extra_css:
  - stylesheets/extra.css

markdown_extensions:
- admonition
- callouts
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
    auto_append: [ ]
    base_path:
      - ./
- pymdownx.tabbed:
    alternate_style: true
- toc:
    permalink: "¤"
- attr_list
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - macros:
      include_yaml:
        - copier: .copier-answers.yml
        - task: Taskfile.yaml
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
      fallback_to_build_date: true
  - gen-files:
      scripts:
        - docs/docs.py
  - literate-nav:
      nav_file: docs/reference/SUMMARY.md
  - section-index
  - coverage:
      html_report_dir: dist/coverage/
  - mkdocstrings

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/irangareddy
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/eccenca
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/cmem-plugin-base/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/irangareddy

nav:
  - Getting Started: getting-started.md
  - How-To Guides: how-to-guides/
  - Code Reference: reference/
  - About:
      - Contributing: about/contributing.md
      - Changelog: about/changelog.md
      - Coverage report: coverage.md
